version: '3.8'

services:
  footyapp-web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/app
    environment:
      - TZ=Europe/London