version: '3.8'

services:
  footyapp-web:
    image: ghcr.io/bignellrp/footyapp-web:main
    container_name: footyapp-web-${BRANCH}
    networks:
      br0:
        ipv4_address: 192.168.0.230
    ports:
      - "80:80"
    restart: always
    env_file:
      - /mnt/docker/footyapp-web/.env

networks:
  br0:
    external: true
    name: br0