version: '3.8'

services:
  footyapp-web:
    image: ghcr.io/bignellrp/footyapp-web:${BRANCH}
    container_name: footyapp-web-${BRANCH}
    networks:
      - br1
    ports:
      - "8${PORT}:80"
    restart: always
    env_file:
      - /mnt/docker/footyapp-web-${BRANCH}/.env
    environment:
      - TZ=Europe/London

networks:
  br1:
    external: true
    name: br1