from routes.compare import compare_blueprint
from routes.index import index_blueprint
from routes.leaderboard import leaderboard_blueprint
from routes.stats import stats_blueprint
from routes.result import result_blueprint
from routes.score import score_blueprint
from routes.login import login_blueprint
from routes.logout import logout_blueprint
from routes.player import player_blueprint
from routes.swap import swap_blueprint