name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag and Push Docker Image to GHCR
        uses: GlueOps/github-actions-build-push-containers@v0.1.3

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'footyapp-web'
          stack-definition: 'docker-compose.yml'
          template-variables: '{"BRANCH": "main"}'
          image: ghcr.io/bignellrp/footyapp-web:main
          prune-stack: true
          pull-image: true