name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag and Push Docker Image to GHCR
        uses: GlueOps/github-actions-build-push-containers@v0.1.3

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Set up webhook secret based on branch
        id: set_secret
        env:
          WEBHOOK_SECRET_MAIN: ${{ secrets.WEBHOOK_MAIN }}
          WEBHOOK_SECRET_DEV: ${{ secrets.WEBHOOK_DEV }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "WEBHOOK_SECRET=$WEBHOOK_SECRET_MAIN" >> $GITHUB_ENV
          else
            echo "WEBHOOK_SECRET=$WEBHOOK_SECRET_DEV" >> $GITHUB_ENV
          fi

      - name: Send Rebuild Request to Portainer
        env:
          PORTAINER_TOKEN: ${{ secrets.PORTAINER_TOKEN }}
          WEBHOOK_SECRET: ${{ env.WEBHOOK_SECRET }}
        run: |
          curl -X POST \
                -H "Authorization: Bearer $PORTAINER_TOKEN" \
                -H "Content-Type: application/json" \
                $WEBHOOK_SECRET