name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag and Push Docker Image to GHCR
        uses: GlueOps/github-actions-build-push-containers@v0.1.3

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Send Rebuild Request to Portainer
        run: |
          curl -X POST \
                -H "Authorization: Bearer ${{ secrets.PORTAINER_TOKEN }}" \
                -H "Content-Type: application/json" \
                ${{ secrets.PORTAINER_WEBHOOK }}